Completed css-grid-classes -note i need to slow down
owen-adams2021/c0121-code-solutions pull request #17
Opened 2021-01-21 22:57 UTC by owen-adams2021

![image](https://user-images.githubusercontent.com/76730244/105422681-2a133280-5c12-11eb-99b1-352d53b7afe3.png)

2021-01-21 23:10 UTC, codingcodymiller requested changes
Hey Owen! Good work so far, one minor fix:

2021-01-21 23:10 UTC, codingcodymiller commented on css-grid-classes/styles.css
> +  justify-content: center;
This is not a flex container, so this has no effect, and should be removed.

2021-01-21 23:17 UTC, owen-adams2021 commented
![image](https://user-images.githubusercontent.com/76730244/105424219-fd144f00-5c14-11eb-9556-b01c726dc14d.png)

2021-01-22 20:49 UTC, codingcodymiller approved these changes
Nicely done!! 👍

2021-01-22 20:56 UTC, merged