Re-committing because of text errors
owen-adams2021/c0121-code-solutions pull request #19
Opened 2021-01-22 18:11 UTC by owen-adams2021

![image](https://user-images.githubusercontent.com/76730244/105528714-516e0c00-5cb3-11eb-86ab-2c4d15a6fec3.png)

I'm not finished with the button

2021-01-22 18:12 UTC, owen-adams2021 commented
Font* errors, not text errors. Screenshot is in our Slack messages.

2021-01-22 21:35 UTC, owen-adams2021 commented
![image](https://user-images.githubusercontent.com/76730244/105550835-e1ba4a00-5ccf-11eb-8121-0db8d0e916d7.png)

2021-01-23 03:43 UTC, codingcodymiller requested changes
Nice job so far! A little revision needed:

2021-01-23 03:43 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
This doesn't represent a half column as you used it in your document. Each of the elements with this class is a row taking up the full width. I would suggest that you make this a `row` class, then add a `column-half` class (that actually is `50%` width) to each of the `.content` elements.

2021-01-23 22:34 UTC, owen-adams2021 commented
![image](https://user-images.githubusercontent.com/76730244/105615782-37125c00-5da1-11eb-90cf-2eeee5430ca8.png)

I'm glad you noticed this, at the time I couldn't figure it out so I just swapped paragraphs around.

2021-01-27 02:51 UTC, codingcodymiller requested changes
Great improvement! A few more changes for you:

2021-01-27 02:51 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.container1 {
This should just stay `.container`

2021-01-27 02:51 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  flex-wrap: flex;
This line can be removed, the value is invalid.

2021-01-27 02:51 UTC, codingcodymiller commented on css-two-column-layout/index.html
> +      <div class="column-half">
I see you added the `column-half` class, but it doesn't have any styling associated with it. You should create a CSS rule for the class, and apply a `width` property set to `50%`.

2021-01-27 03:41 UTC, owen-adams2021 commented on css-two-column-layout/styles.css
> +.container1 {
![image](https://user-images.githubusercontent.com/76730244/105939620-941f4380-6027-11eb-8f68-9b85f1a53033.png)

2021-01-27 03:41 UTC, owen-adams2021 commented on css-two-column-layout/styles.css
> +  flex-wrap: flex;
![image](https://user-images.githubusercontent.com/76730244/105939633-9e414200-6027-11eb-8120-3277d9174465.png)

2021-01-27 03:42 UTC, owen-adams2021 commented on css-two-column-layout/index.html
> +      <div class="column-half">
![image](https://user-images.githubusercontent.com/76730244/105939668-ae592180-6027-11eb-8b29-9d4c4544feac.png)

2021-01-27 03:42 UTC, owen-adams2021 commented
Thank you for clearing this up - flood me with your knowledge.

2021-01-27 17:16 UTC, codingcodymiller approved these changes
Nicely done!!!

2021-01-27 17:35 UTC, merged