Css canvas medical
owen-adams2021/c0121-code-solutions pull request #21
Opened 2021-01-25 07:01 UTC by owen-adams2021

![image](https://user-images.githubusercontent.com/76730244/105671704-251fde80-5eb1-11eb-9677-10b017796f03.png)

2021-01-28 19:38 UTC, thebearingedge requested changes
Ok great job so far. Just two general notes
- make some generic grid classes, like `.row` and `.column-half` that you can use in multiple places
- stick with `lower-kebab-case` for your CSS class named instead of `camelCase`.

2021-01-28 19:38 UTC, thebearingedge commented on css-canvas-medical/styles.css
> +  text-decoration: none !important;
Are you sure this `!important` is necessary?

2021-01-29 05:09 UTC, owen-adams2021 commented on css-canvas-medical/styles.css
> +  text-decoration: none !important;
Nope! Just removed it and my links did not change. I remember having issues with the links and this fixed it, however I'm not having issues anymore without `!important`

2021-01-29 05:33 UTC, owen-adams2021 commented on css-canvas-medical/styles.css
> +  text-decoration: none !important;
Are you wanting me to implement these changes to class names on this web page, or going forward? Also, I'm getting ahead of myself here, for this particular challenge can I use separate stylesheets for separate web pages?

2021-01-29 18:44 UTC, thebearingedge commented on css-canvas-medical/styles.css
> +  text-decoration: none !important;
> can I use separate stylesheets for separate web pages?
yes 👍 The stuff that is common among the pages can all go in one stylesheet though to avoid copy-pasted CSS.

2021-01-29 18:45 UTC, thebearingedge commented on css-canvas-medical/styles.css
> +  text-decoration: none !important;
> Are you wanting me to implement these changes to class names on this web page, or going forward?

Yes and yes 😄

2021-01-30 18:02 UTC, thebearingedge requested changes
Hey Owen, I'm just marking this as changes requested for now until [these changes](https://github.com/owen-adams2021/c0121-code-solutions/pull/21#discussion_r567021501) are done, so our reports are up-to-date.

2021-02-06 04:24 UTC, owen-adams2021 commented
![image](https://user-images.githubusercontent.com/76730244/107108847-3c43c200-6809-11eb-9074-58b3a951b48c.png)

2021-02-06 18:10 UTC, thebearingedge approved these changes
Much better 👏

2021-02-06 18:22 UTC, merged