Css ecommerce page
owen-adams2021/c0121-code-solutions pull request #37
Opened 2021-02-01 04:54 UTC by owen-adams2021

![image](https://user-images.githubusercontent.com/76730244/106416575-b2b67d80-641f-11eb-936e-0a9a1220c914.png)

2021-02-01 17:03 UTC, thebearingedge requested changes
Hi Owen, just a few notes on your solution.

- The background color should be left as white for this one.
- Try to reorganize your HTML into columns.
- The sale prices should have a subtle background color to them.

2021-02-01 17:03 UTC, thebearingedge commented on css-ecommerce-page/styles.css
> +  object-position: 20% 10%; */
Please delete commented out code before turning in your solution.

2021-02-02 17:25 UTC, owen-adams2021 commented
Updated Screenshot
![image](https://user-images.githubusercontent.com/76730244/106638248-ab8f8c80-6551-11eb-894d-e50c249c6e35.png)

2021-02-02 19:27 UTC, codingcodymiller requested changes
Hey Owen! Rather than grouping the images and text into separate rows, you should have one `row` container with each image and relevant text for that image in its own `column` container. Please reformat the HTML and do any revisions necessary to your CSS as a result of the change, then resubmit.

2021-02-03 00:26 UTC, codingcodymiller requested changes
Hey Owen! The changes look good in the code, but please provide an updated screenshot after the changes you made to make sure everything still looks correct 👍

2021-02-03 04:15 UTC, owen-adams2021 commented
![image](https://user-images.githubusercontent.com/76730244/106697344-8c721880-65ac-11eb-88b1-f923476805f6.png)

2021-02-03 15:39 UTC, thebearingedge approved these changes

2021-02-03 17:39 UTC, merged