Completed JavaScript Modal Exercise
owen-adams2021/c0121-code-solutions pull request #43
Opened 2021-02-03 03:55 UTC by owen-adams2021

![image](https://user-images.githubusercontent.com/76730244/106695946-a6f6c280-65a9-11eb-9c3e-b6a934c2d05e.png)

2021-02-03 15:16 UTC, thebearingedge requested changes

2021-02-03 15:16 UTC, thebearingedge commented on javascript-modal/main.js
> +  $openModal.className = 'open-modal';
You only need to show/hide the black backdrop element, these extra CSS classes should not be necessary.

2021-02-03 15:16 UTC, thebearingedge commented on javascript-modal/styles.css
> +  margin-top: 30vh;
Instead of a huge `margin-top`, use `display: flex` on your `.open-modal` and then the appropriate flex properties to center the `.pop-up` inside of it.

2021-02-03 15:16 UTC, thebearingedge commented on javascript-modal/styles.css
> +}
The modal (backdrop and popup) should "cover" the button that triggers it to open. So this `pointer-events` should not be necessary.

2021-02-06 17:56 UTC, owen-adams2021 commented
After reading your input, it made me want to re-do the whole thing. I had forgotten about the `position: absolute` key value pair for CSS. Thank you for the insight! 

![image](https://user-images.githubusercontent.com/76730244/107125939-b6f8f580-687a-11eb-8d2e-c995621b2988.png)

2021-02-06 18:02 UTC, thebearingedge approved these changes

2021-02-06 18:09 UTC, merged