Javascript bank
owen-adams2021/c0121-code-solutions pull request #65
Opened 2021-02-21 02:43 UTC by owen-adams2021

![image](https://user-images.githubusercontent.com/76730244/108613995-a7be8f80-73c4-11eb-8c54-76e0e2d9c3f4.png)

2021-02-21 21:19 UTC, thebearingedge requested changes

2021-02-21 21:19 UTC, thebearingedge commented on javascript-bank/bank.js
> +    account.transactions.push(newTransaction);
Use the account's `deposit` method to deposit the beginning balance.

2021-02-22 02:35 UTC, owen-adams2021 commented
Updated screenshot

![image](https://user-images.githubusercontent.com/76730244/108650068-b2445c00-748c-11eb-9589-f80d25d86c7f.png)

2021-02-22 02:39 UTC, thebearingedge approved these changes

2021-02-22 02:40 UTC, merged